### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by wojas** [fusionbox/django-widgy#207]
Widgy currently does not support Python 3, but it should.

I make an attempt to get it up and running. It required bleeding edge versions of a few dependencies and a few patches, but I got it up to a level where it installs, the server runs and the admin can be displayed with Python 3.4 and Django 1.6. Pull requests have been sent to the authors of the affected repositories.

The project and required dependencies can be found here:
https://github.com/wojas/django-widgy-website-py3
This repository can be the starting point for Python 3 development and testing. You can have the project up and running in a minute.

I'm new to Widgy, so I often cannot even judge what's expected behaviour, what's a configuration error and what's a real bug. It would be great if any Widgy developers would have the time to take a look at it and help solve any remaining issues.

**Comment by gavinwahl** [comment]
Replaced by #312. Thanks @wojas
