### ISSUE TITLE
Trimmed requirements for those who don't use Mezzanine

### ISSUE THREAD

**Issue by andybak** [fusionbox/django-widgy#218]
I wanted to investigate building Widgy into my CMS so I pip installed it. 

After a lot of churning I ended up with: mezzanine django-treebeard django-filer django-polymorphic PyScss markdown bleach beautifulsoup4 html2text phonenumbers django-argonauts filebrowser-safe grappelli-safe tzlocal requests requests-oauthlib future easy-thumbnails django-mptt html5lib pytz oauthlib

I definitely don't want Mezzanine or Grappelli - I have my own CMS and my own admin skin. I also have my own fork of Django filebrowser. A lot of the other requirements seem rather orthogonal to Widgy's stated intent but it's not clear which can be safely removed.

**Comment by gavinwahl** [comment]
This is fixed now right?
