### ISSUE TITLE
Pre-release version number doesn't follow PEP-440

### ISSUE THREAD

**Issue by gavinwahl** [fusionbox/django-widgy#297]
We're adding the current git commit to the version number in a way not conforming to PEP-440:

>  UserWarning: The version specified ('0.4.0-039dedd4') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.

**Comment by rockymeza** [comment]
Want to move to zest.releaser?

**Comment by rockymeza** [comment]
Fixed in https://github.com/fusionbox/django-widgy/commit/906f043f57a9838e20d10f64e118dca17602fb5c
