### ISSUE TITLE
It is possible to delete forms that have submissions

### ISSUE THREAD

**Issue by jxcl** [fusionbox/django-widgy#318]
Steps to reproduce:

- Add a form to a main content in Widgy.
- Add a submission to that form
- Delete the form

Expected:

Widgy should inform the user that the form has protected related objects, and that the form cannot be deleted.

Observed:

Widgy displays the delete button and an error is generated when the button is clicked:

```
ProtectedError: ("Cannot delete some instances of model 'Node' because they are referenced through a protected foreign key: 'FormSubmission.form_node'", [<FormSubmission: FormSubmission object>])
```

**Comment by acatton** [comment]
This is a bug in grappelli_safe, this was fixed by gavin [here](https://github.com/stephenmcd/grappelli-safe/commit/03ab4052a36ae4175e90d0f5a9c559cf3960fa02)
