### ISSUE TITLE
Provide pre-compiled static assets

### ISSUE THREAD

**Issue by rockymeza** [fusionbox/django-widgy#320]
There are some deployment situations where using django-compressor is not very compatible.

I think we should provide a pre-compiled version of the static assets that makes it easy to deploy with requiring django-compressor, django-pyscss, or pyscss.

I don't know how to do this, but I think we should start discussing it.

**Comment by gavinwahl** [comment]
Can you use django-compressor's offline mode?

**Comment by rockymeza** [comment]
I can't get it to work. It seems to fail with mezzanine's templates and also it doesn't support overextends.

**Comment by gavinwahl** [comment]
<https://www.fusionbox.com/blog/detail/how-to-use-django-compressor-offline-compression-with-widgy/570/>
