### ISSUE TITLE
Preview button when not using mezzanine

### ISSUE THREAD

**Issue by PhilipGarnero** [fusionbox/django-widgy#332]
It would be great to have a preview button in the admin when using widgy's page builder without mezzanine.

See #331 for this setup

**Comment by gavinwahl** [comment]
Hi Philip,

You can use the get_action_links method on your owner (briefly mentioned here http://docs.wid.gy/en/latest/design/owners.html) to add buttons to the widgy editor. It's not possible to have a generic preview button, because you have to provide the view to do previewing.

**Comment by PhilipGarnero** [comment]
Oh great ! Thank you !
You should maybe add this somewhere more obvious in the docs.
I think widgy's huge area of improvement is the doc.
You could try to make it more user friendly =)
