### ISSUE TITLE
Unrestricted File Upload Vulnerability in demo site

### ISSUE THREAD

**Issue by HatBoy** [fusionbox/django-widgy#387]
Hi, I would like to report unrestricted file upload vulnerability in demo site.

Description:
Unrestricted File Upload Vulnerability in demo site image widget.

Steps To Reproduce:
1. First in the page builder create a image widget and edit it.
![1](https://user-images.githubusercontent.com/8274796/60870700-f1944980-a263-11e9-8802-e53bd070c94c.png)
2. Then upload file, you can upload any file you want.
![2](https://user-images.githubusercontent.com/8274796/60870723-fa851b00-a263-11e9-8787-9f216f5359bb.png)
3. Find you upload file URL
![3](https://user-images.githubusercontent.com/8274796/60870735-fe18a200-a263-11e9-8990-67b880feee4e.png)
4. Open the URL you can see the page execution
![4](https://user-images.githubusercontent.com/8274796/60870750-01ac2900-a264-11e9-91a0-d5eac228c34f.png)

author by jin.dong@dbappsecurity.com.cn

**Comment by gavinwahl** [comment]
Thank you, this has been fixed.
